In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
df = pd.read_csv('Titanic-Dataset.csv')
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [4]:
df.describe()

       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071  ...    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000  ...    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000  ...    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000  ...    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000  ...    8.000000    6.000000  512.329200

[8 rows x 7 columns]

In [5]:
df['FamilySize'] = df['SibSp'] + df['Parch'] +1
df['IsAlone'] = (df['FamilySize']==1).astype(int)

In [6]:
df['TicketGroupSize'] = df.groupby('Ticket')['Ticket'].transform('count')

In [7]:
df['HasCabin'] = df['Cabin'].notnull().astype(int)

In [8]:
df['Title'] = df['Name'].str.extract(r'([A-Za-z]+)\.',expand=False)
df['Title'].value_counts()

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Col           2
Mlle          2
Major         2
Ms            1
Mme           1
Don           1
Lady          1
Sir           1
Capt          1
Countess      1
Jonkheer      1
Name: count, dtype: int64

In [9]:
df['Title'] = df['Title'].replace(['Col','Major','Dr','Rev','Lady','Capt','Countess','Jonkheer','Sir','Don'],'Rare').replace(['Ms','Mlle'],'Miss').replace('Mme','Mrs')

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize', 'IsAlone',
       'TicketGroupSize', 'HasCabin', 'Title'],
      dtype='object')

In [11]:
df['Title'].value_counts()

Title
Mr        517
Miss      185
Mrs       126
Master     40
Rare       23
Name: count, dtype: int64

In [12]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin'],axis=1,inplace=True)

In [13]:
df

     Survived  Pclass     Sex   Age  ...  IsAlone TicketGroupSize  HasCabin  Title
0           0       3    male  22.0  ...        0               1         0     Mr
1           1       1  female  38.0  ...        0               1         1    Mrs
2           1       3  female  26.0  ...        1               1         0   Miss
3           1       1  female  35.0  ...        0               2         1    Mrs
4           0       3    male  35.0  ...        1               1         0     Mr
..        ...     ...     ...   ...  ...      ...             ...       ...    ...
886         0       2    male  27.0  ...        1               1         0   Rare
887         1       1  female  19.0  ...        1               1         1   Miss
888         0       3  female   NaN  ...        0               2         0   Miss
889         1       1    male  26.0  ...        1               1         1     Mr
890         0       3    male  32.0  ...        1               1         0     Mr

[891 rows x 11 columns]

In [14]:
#Split Features and Labels
X = df.drop('Survived',axis=1)
Y = df['Survived']

In [15]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [16]:
num_att = X_train.select_dtypes(include=[np.number]).columns.tolist()
cat_att = X_train.select_dtypes(exclude=[np.number]).columns.tolist()

In [17]:
num_pipe = make_pipeline(SimpleImputer(strategy='median'))
cat_pipe = make_pipeline(SimpleImputer(strategy='most_frequent'),OneHotEncoder(handle_unknown='ignore'))
full_pipe = ColumnTransformer([
    ('num',num_pipe,num_att),
    ('cat',cat_pipe,cat_att)
])

In [18]:
num_scaled = make_pipeline(SimpleImputer(strategy='median'),StandardScaler())
full_scaled =ColumnTransformer([
    ('num',num_scaled,num_att),
    ('cat',cat_pipe,cat_att)
])

In [19]:
rf_pipe=make_pipeline(full_pipe,RandomForestClassifier(random_state=42))

In [20]:
rf_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Pclass', 'Age', 'Fare',
                                                   'FamilySize', 'IsAlone',
                                                   'TicketGroupSize',
                                                   'HasCabin']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked',
                                                   'Title'])])),
                ('randomforestclassifier',
                 RandomForestClassifier(random_state=42))])

In [ ]:
rf_pred = rf_pipe.predict(X_test)
rf_accuracy = accuracy_score(Y_test,rf_pred)

In [22]:
rf_accuracy

0.8212290502793296

In [24]:
xgb_pipe = make_pipeline(full_pipe,XGBClassifier())
xgb_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Pclass', 'Age', 'Fare',
                                                   'FamilySize', 'IsAlone',
                                                   'TicketGroupSize',
                                                   'HasCabin']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [25]:
xgb_pred = xgb_pipe.predict(X_test)
xgb_accuracy =accuracy_score(Y_test,xgb_pred)

In [26]:
xgb_accuracy

0.7932960893854749

In [27]:
lr_pipe = make_pipeline(full_scaled,LogisticRegression(max_iter=1000))
lr_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['Pclass', 'Age', 'Fare',
                                                   'FamilySize', 'IsAlone',
                                                   'TicketGroupSize',
                                                   'HasCabin']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked',
                                                   'Title'])])),
                ('logisticregression', LogisticRegression(max_iter=1000))])

In [28]:
lr_pred = lr_pipe.predict(X_test)
lr_accuracy = accuracy_score(Y_test,lr_pred)

In [29]:
lr_accuracy

0.8324022346368715

In [30]:
svm_pipe = make_pipeline(full_scaled,SVC(kernel='rbf'))
svm_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['Pclass', 'Age', 'Fare',
                                                   'FamilySize', 'IsAlone',
                                                   'TicketGroupSize',
                                                   'HasCabin']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked',
                                                   'Title'])])),
                ('svc', SVC())])

In [31]:
svm_pred =svm_pipe.predict(X_test)
svm_accuracy = accuracy_score(Y_test,svm_pred)

In [32]:
svm_accuracy

0.8324022346368715

In [33]:
grid = GridSearchCV(
    estimator=rf_pipe,
    param_grid={
        'randomforestclassifier__n_estimators': [100, 150, 200],
        'randomforestclassifier__max_depth': [5, 10, None]
    },
    cv=5
)
grid.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median'))]),
                                                                         ['Pclass',
                                                                          'Age',
                                                                          'Fare',
                                                                          'FamilySize',
                                                                          'IsAlone',
                                                                          'TicketGroupSize',
                                                                          'HasCabin']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          OneHotEncoder(handle_unknown='ignore'))]),
                                                                         ['Sex',
                                                                          'Embarked',
                                                                          'Title'])])),
                                       ('randomforestclassifier',
                                        RandomForestClassifier(random_state=42))]),
             param_grid={'randomforestclassifier__max_depth': [5, 10, None],
                         'randomforestclassifier__n_estimators': [100, 150,
                                                                  200]})

In [34]:
best_rf =grid.best_estimator_

In [35]:
grid.best_params_

{'randomforestclassifier__max_depth': 5,
 'randomforestclassifier__n_estimators': 150}

In [36]:
best_rf_pred =best_rf.predict(X_test)
best_rf_accuracy = accuracy_score(Y_test,best_rf_pred)

In [37]:
best_rf_accuracy

0.8268156424581006

In [38]:
grid_xgb = GridSearchCV(
    estimator=xgb_pipe,
    param_grid={
        'xgbclassifier__n_estimators': [100, 150, 200],
        'xgbclassifier__max_depth': [5, 10, None],
        'xgbclassifier__learning_rate':[0.05,0.1,0.2],
        'xgbclassifier__subsample':[0.5,0.8],
        'xgbclassifier__colsample_bytree':[0.5,0.8]
    },
    cv=5
)
grid_xgb.fit(X_train,Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median'))]),
                                                                         ['Pclass',
                                                                          'Age',
                                                                          'Fare',
                                                                          'FamilySize',
                                                                          'IsAlone',
                                                                          'TicketGroupSize',
                                                                          'HasCabin']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('onehotencoder',
                                                                                          On...
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None, ...))]),
             param_grid={'xgbclassifier__colsample_bytree': [0.5, 0.8],
                         'xgbclassifier__learning_rate': [0.05, 0.1, 0.2],
                         'xgbclassifier__max_depth': [5, 10, None],
                         'xgbclassifier__n_estimators': [100, 150, 200],
                         'xgbclassifier__subsample': [0.5, 0.8]})

In [39]:
grid_xgb_predict =grid_xgb.predict(X_test)
grid_xgb_accuracy = accuracy_score(Y_test,grid_xgb_predict)

In [40]:
grid_xgb_accuracy

0.8324022346368715

In [44]:
nb_pipe = make_pipeline(full_scaled,GaussianNB())
nb_pipe.fit(X_train,Y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['Pclass', 'Age', 'Fare',
                                                   'FamilySize', 'IsAlone',
                                                   'TicketGroupSize',
                                                   'HasCabin']),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked',
                                                   'Title'])])),
                ('gaussiannb', GaussianNB())])

In [45]:
nb_pred = nb_pipe.predict(X_test)
nb_accuracy = accuracy_score(Y_test,nb_pred)

In [46]:
nb_accuracy

0.8044692737430168

In [47]:
Models = pd.DataFrame ({
    'Model':['RandomForestClassifier','XGBClassifier','LogisticRegression','SVM','NaiveBayes','BestRandomForest','BestXGB'],
    'Accuracy':[0.82,0.79,0.83,0.83,0.80,0.82,0.83]
})

In [48]:
Models

                    Model  Accuracy
0  RandomForestClassifier      0.82
1           XGBClassifier      0.79
2      LogisticRegression      0.83
3                     SVM      0.83
4              NaiveBayes      0.80
5        BestRandomForest      0.82
6                 BestXGB      0.83

In [49]:
xgb_cm = confusion_matrix(Y_test,xgb_pred)
xgb_cm

array([[88, 17],
       [20, 54]])

In [ ]:
#Confusion matrix of Best  Model
xgb_cm = pd.DataFrame(
    xgb_cm,
    index=["Actual 0", "Actual 1"],
    columns=["Predicted 0", "Predicted 1"]
)

xgb_cm

          Predicted 0  Predicted 1
Actual 0           88           17
Actual 1           20           54